// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:yellow_group_flutterapp/models/annoucement_model.dart';
import 'package:yellow_group_flutterapp/models/cafeteria_item.dart';
import 'package:yellow_group_flutterapp/models/campus_model.dart';
import 'package:yellow_group_flutterapp/models/event_item.dart';
import 'package:yellow_group_flutterapp/models/news_model.dart';
import 'package:yellow_group_flutterapp/models/school_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnnoucementCallAdapter());
    registerAdapter(CafeteriaItemAdapter());
    registerAdapter(CampusCallAdapter());
    registerAdapter(EventCallAdapter());
    registerAdapter(NewsCallAdapter());
    registerAdapter(SchoolCallAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnnoucementCallAdapter());
    registerAdapter(CafeteriaItemAdapter());
    registerAdapter(CampusCallAdapter());
    registerAdapter(EventCallAdapter());
    registerAdapter(NewsCallAdapter());
    registerAdapter(SchoolCallAdapter());
  }
}
